package com.yaphetzhao.peargreendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PEAR_NOTE".
 */
public class PearNote {

    private Long id;
    /** Not-null value. */
    private String key;
    private String value;
    private String createtime;
    private java.util.Date PearNoteDAO;

    public PearNote() {
    }

    public PearNote(Long id) {
        this.id = id;
    }

    public PearNote(Long id, String key, String value, String createtime, java.util.Date PearNoteDAO) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.createtime = createtime;
        this.PearNoteDAO = PearNoteDAO;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public java.util.Date getPearNoteDAO() {
        return PearNoteDAO;
    }

    public void setPearNoteDAO(java.util.Date PearNoteDAO) {
        this.PearNoteDAO = PearNoteDAO;
    }

}
