package com.yaphetzhao.peargreendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yaphetzhao.peargreendao.bean.PearNote;

import com.yaphetzhao.peargreendao.dao.PearNoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pearNoteDaoConfig;

    private final PearNoteDao pearNoteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pearNoteDaoConfig = daoConfigMap.get(PearNoteDao.class).clone();
        pearNoteDaoConfig.initIdentityScope(type);

        pearNoteDao = new PearNoteDao(pearNoteDaoConfig, this);

        registerDao(PearNote.class, pearNoteDao);
    }
    
    public void clear() {
        pearNoteDaoConfig.getIdentityScope().clear();
    }

    public PearNoteDao getPearNoteDao() {
        return pearNoteDao;
    }

}
